version: '3.7'
services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
  # app:
  #   container_name: app
  #   build: ./
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - "3000:3000"
